--
-- PostgreSQL database dump
--

\restrict Pn1lVhVaMSpbaxF9nG9MOznGUlSDA6rrzwflaOX9FVZYoSgkTgiIZ7vXa3j37vN

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: auctions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auctions (
    auction_id integer NOT NULL,
    name character varying(150),
    start_time timestamp with time zone CONSTRAINT auctions_auction_date_not_null NOT NULL,
    status text NOT NULL,
    insurance_details text,
    location_id integer,
    microchip_id character varying(50),
    base_price numeric DEFAULT 0.0 NOT NULL,
    created_by_id integer,
    current_bid numeric DEFAULT 0.0 NOT NULL,
    end_time timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    minimum_increment numeric DEFAULT 0.0 NOT NULL,
    video_url character varying(255),
    winner_id integer,
    image_url character varying(255)
);


ALTER TABLE public.auctions OWNER TO postgres;

--
-- Name: auctions_auction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auctions ALTER COLUMN auction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auctions_auction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bids; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bids (
    id integer NOT NULL,
    auction_id integer NOT NULL,
    bidder_id integer NOT NULL,
    amount numeric NOT NULL,
    "timestamp" timestamp with time zone NOT NULL
);


ALTER TABLE public.bids OWNER TO postgres;

--
-- Name: bids_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bids ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bids_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: colours; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.colours (
    colour_id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.colours OWNER TO postgres;

--
-- Name: colours_colour_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.colours ALTER COLUMN colour_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.colours_colour_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equine_vets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equine_vets (
    vet_id integer NOT NULL,
    ssn character varying(20) NOT NULL,
    veterinary_license character varying(100) NOT NULL
);


ALTER TABLE public.equine_vets OWNER TO postgres;

--
-- Name: health_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.health_records (
    health_id integer NOT NULL,
    diagnosis text NOT NULL,
    treatment text NOT NULL,
    visit_date timestamp with time zone NOT NULL,
    notes text,
    microchip_id character varying(50) NOT NULL,
    vet_id integer
);


ALTER TABLE public.health_records OWNER TO postgres;

--
-- Name: health_records_health_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.health_records ALTER COLUMN health_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_records_health_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: horse_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.horse_profiles (
    microchip_id character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    age integer,
    gender character varying(10),
    breed character varying(50) NOT NULL,
    life_status character varying(50) NOT NULL,
    birthdate timestamp with time zone,
    image_url character varying(255),
    pedigree_image_url character varying(255),
    colour_id integer,
    owner_id integer,
    stud_id integer,
    ped_id integer,
    pedigree_ped_id integer,
    claim_location character varying(255),
    health_status character varying(50),
    is_approved boolean DEFAULT false NOT NULL,
    is_for_sale boolean DEFAULT false NOT NULL,
    price numeric,
    racing_history character varying(255),
    vaccinated boolean DEFAULT false NOT NULL,
    video_url character varying(255)
);


ALTER TABLE public.horse_profiles OWNER TO postgres;

--
-- Name: horse_training_enrollments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.horse_training_enrollments (
    enrollment_id integer NOT NULL,
    microchip_id character varying(50) NOT NULL,
    program_id integer NOT NULL,
    enrollment_date timestamp with time zone NOT NULL,
    performance_score integer,
    notes text
);


ALTER TABLE public.horse_training_enrollments OWNER TO postgres;

--
-- Name: horse_training_enrollments_enrollment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.horse_training_enrollments ALTER COLUMN enrollment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.horse_training_enrollments_enrollment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.locations (
    location_id integer NOT NULL,
    government character varying(100) NOT NULL,
    city character varying(100) NOT NULL,
    address text NOT NULL
);


ALTER TABLE public.locations OWNER TO postgres;

--
-- Name: locations_location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.locations ALTER COLUMN location_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maneges; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maneges (
    manege_id integer NOT NULL,
    name character varying(150) NOT NULL,
    type character varying(50),
    surface_type character varying(50),
    status character varying(50) NOT NULL,
    capacity integer NOT NULL,
    availability_schedule text,
    location_id integer
);


ALTER TABLE public.maneges OWNER TO postgres;

--
-- Name: maneges_manege_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maneges ALTER COLUMN manege_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maneges_manege_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id integer NOT NULL,
    sender_id integer NOT NULL,
    receiver_id integer NOT NULL,
    horse_id text,
    content text NOT NULL,
    subject text NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    is_read boolean NOT NULL
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_posts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.news_posts (
    id integer NOT NULL,
    title text NOT NULL,
    description text,
    content text,
    author text,
    source_name text,
    url text NOT NULL,
    url_to_image text,
    published_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.news_posts OWNER TO postgres;

--
-- Name: news_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.news_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: owners; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.owners (
    owner_id integer NOT NULL,
    preferences jsonb,
    since timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public.owners OWNER TO postgres;

--
-- Name: pedigrees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedigrees (
    ped_id integer NOT NULL,
    father_horse_name character varying(150),
    mother_horse_name character varying(150),
    lineage_notes text
);


ALTER TABLE public.pedigrees OWNER TO postgres;

--
-- Name: pedigrees_ped_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pedigrees ALTER COLUMN ped_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedigrees_ped_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_claims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_claims (
    id integer NOT NULL,
    role_id integer NOT NULL,
    claim_type text,
    claim_value text
);


ALTER TABLE public.role_claims OWNER TO postgres;

--
-- Name: role_claims_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role_claims ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_claims_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stud_phones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stud_phones (
    phone_id integer NOT NULL,
    stud_id integer NOT NULL,
    phone_number character varying(20) NOT NULL
);


ALTER TABLE public.stud_phones OWNER TO postgres;

--
-- Name: stud_phones_phone_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.stud_phones ALTER COLUMN phone_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stud_phones_phone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: studs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.studs (
    stud_id integer NOT NULL,
    name character varying(150) NOT NULL,
    stud_type character varying(50),
    stall_capacity integer NOT NULL,
    boarding_price numeric NOT NULL,
    num_of_horses integer NOT NULL,
    num_of_males integer NOT NULL,
    num_of_females integer NOT NULL,
    url character varying(255),
    location_id integer
);


ALTER TABLE public.studs OWNER TO postgres;

--
-- Name: studs_stud_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.studs ALTER COLUMN stud_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.studs_stud_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trainers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trainers (
    trainer_id integer NOT NULL,
    experience_years integer NOT NULL,
    bio text
);


ALTER TABLE public.trainers OWNER TO postgres;

--
-- Name: training_programmes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.training_programmes (
    program_id integer NOT NULL,
    name_of_program character varying(150),
    description text,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    price numeric NOT NULL,
    trainer_id integer,
    manege_id integer
);


ALTER TABLE public.training_programmes OWNER TO postgres;

--
-- Name: training_programmes_program_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.training_programmes ALTER COLUMN program_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_programmes_program_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_claims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_claims (
    id integer NOT NULL,
    user_id integer NOT NULL,
    claim_type text,
    claim_value text
);


ALTER TABLE public.user_claims OWNER TO postgres;

--
-- Name: user_claims_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_claims ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_claims_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_logins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_logins (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id integer NOT NULL
);


ALTER TABLE public.user_logins OWNER TO postgres;

--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_id integer NOT NULL,
    role_id integer NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Name: user_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_tokens (
    user_id integer NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text
);


ALTER TABLE public.user_tokens OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    name text,
    created_at timestamp with time zone NOT NULL,
    user_name character varying(256),
    email character varying(256),
    password_hash text,
    phone text,
    access_failed_count integer DEFAULT 0 NOT NULL,
    concurrency_stamp text,
    email_confirmed boolean DEFAULT false NOT NULL,
    lockout_enabled boolean DEFAULT false NOT NULL,
    lockout_end timestamp with time zone,
    normalized_email character varying(256),
    normalized_user_name character varying(256),
    phone_number_confirmed boolean DEFAULT false NOT NULL,
    security_stamp text,
    two_factor_enabled boolean DEFAULT false NOT NULL,
    role text,
    bio text,
    profile_picture_url text,
    last_password_changed_at timestamp with time zone,
    is_verified_bidder boolean DEFAULT false NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" (migration_id, product_version) FROM stdin;
20260110210126_InitialCreate	9.0.0
20260110213418_FixIdentitySchema	9.0.0
20260111110610_AddFullSchema	9.0.0
20260111111202_UpdateUserForProfile	9.0.0
20260111130723_AddLastPasswordChangedAt	9.0.0
20260113194400_AddNewsTable	9.0.0
20260118112616_UpdateHorseSchema	9.0.0
20260130143018_AddMessagesTable	9.0.0
20260130213350_AddIsVerifiedBidder	9.0.0
20260130220156_AddAuctionImage	9.0.0
\.


--
-- Data for Name: auctions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auctions (auction_id, name, start_time, status, insurance_details, location_id, microchip_id, base_price, created_by_id, current_bid, end_time, minimum_increment, video_url, winner_id, image_url) FROM stdin;
5	DarkDragon	2026-01-03 00:16:00+02	WaitingForSeller	\N	\N	H001	-2	2	-2	2026-02-07 00:16:00+02	1000	\N	\N	/uploads/6f30c7db-9b9b-4add-87e8-735c0a902cc9.jpg
\.


--
-- Data for Name: bids; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bids (id, auction_id, bidder_id, amount, "timestamp") FROM stdin;
\.


--
-- Data for Name: colours; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.colours (colour_id, name) FROM stdin;
\.


--
-- Data for Name: equine_vets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.equine_vets (vet_id, ssn, veterinary_license) FROM stdin;
9	33940586958	9393939
3	N/A	N/A
\.


--
-- Data for Name: health_records; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.health_records (health_id, diagnosis, treatment, visit_date, notes, microchip_id, vet_id) FROM stdin;
\.


--
-- Data for Name: horse_profiles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.horse_profiles (microchip_id, name, age, gender, breed, life_status, birthdate, image_url, pedigree_image_url, colour_id, owner_id, stud_id, ped_id, pedigree_ped_id, claim_location, health_status, is_approved, is_for_sale, price, racing_history, vaccinated, video_url) FROM stdin;
H001	أسطورة الشحانية	6	Male	صقلاوي	Alive	\N	/horses/profile_main.png	\N	\N	2	\N	\N	\N	الدوحة، قطر	ممتاز	t	t	1500000	\N	t	\N
H002	وردة الصحراء	5	Female	صقلاوي جدراني	Alive	\N	/auctions/card_1.png	\N	\N	2	\N	\N	\N	الرياض، السعودية	جيد جدًا	t	f	\N	\N	t	\N
H003	فجر العرب	4	Male	كحيلان	Alive	\N	/auctions/card_2.png	\N	\N	2	\N	\N	\N	الرياض، السعودية	ممتاز	t	t	850000	\N	t	\N
H004	أميرة الوادي	2	Female	عبية الشراك	Alive	\N	/auctions/hero.png	\N	\N	2	\N	\N	\N	جدة، السعودية	ممتاز	t	f	\N	\N	f	\N
\.


--
-- Data for Name: horse_training_enrollments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.horse_training_enrollments (enrollment_id, microchip_id, program_id, enrollment_date, performance_score, notes) FROM stdin;
\.


--
-- Data for Name: locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.locations (location_id, government, city, address) FROM stdin;
\.


--
-- Data for Name: maneges; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.maneges (manege_id, name, type, surface_type, status, capacity, availability_schedule, location_id) FROM stdin;
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messages (id, sender_id, receiver_id, horse_id, content, subject, "timestamp", is_read) FROM stdin;
1	9	2	H003	بكام الحصان دا؟	استفسار بخصوص الخيل: فجر العرب	2026-01-30 16:47:52.460976+02	f
2	9	2	H002	how much	استفسار بخصوص الخيل: وردة الصحراء	2026-01-30 17:48:52.090278+02	f
3	2	2	H003	بكام؟	استفسار بخصوص الخيل: فجر العرب	2026-01-30 21:42:47.087312+02	f
4	9	2	H003	نوع	استفسار بخصوص الخيل: فجر العرب	2026-01-30 21:44:25.1664+02	f
5	9	2	H002	how much	استفسار بخصوص الخيل: وردة الصحراء	2026-01-30 21:46:39.474251+02	t
\.


--
-- Data for Name: news_posts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.news_posts (id, title, description, content, author, source_name, url, url_to_image, published_at, created_at) FROM stdin;
1	سُئل أعضاء مجلس الشيوخ شركة Meta عن سبب تأخيرها في جعل حسابات القُصّر خاصة افتراضيًا.	A group of senators has written a letter to Meta CEO Mark Zuckerberg asking why his company delayed launching key protections for users under 18. The letter, signed by Brian Schatz (D-HI), Katie Britt (R-AL), Amy Klobuchar (D-MN), James Lankford (R-OK), and C…	<div id="readability-page-1" class="page"><div><div><p><a href="https://www.theverge.com/authors/emma-roth"><img alt="Emma Roth" data-chromatic="ignore" loading="lazy" width="36" height="36" decoding="async" data-nimg="1" srcset="https://platform.theverge.com/wp-content/uploads/sites/2/chorus/author_profile_images/195810/EMMA_ROTH.0.jpg?quality=90&amp;strip=all&amp;crop=0%2C0%2C100%2C100&amp;w=48 1x, https://platform.theverge.com/wp-content/uploads/sites/2/chorus/author_profile_images/195810/EMMA_ROTH.0.jpg?quality=90&amp;strip=all&amp;crop=0%2C0%2C100%2C100&amp;w=96 2x" src="https://platform.theverge.com/wp-content/uploads/sites/2/chorus/author_profile_images/195810/EMMA_ROTH.0.jpg?quality=90&amp;strip=all&amp;crop=0%2C0%2C100%2C100&amp;w=96"></a></p><div><p><span aria-expanded="false" aria-haspopup="true" role="button" tabindex="0"><span id="follow-author-standard_article_details-dmcyOmF1dGhvclByb2ZpbGU6MTE2"><span><span><svg width="9" height="9" viewBox="0 0 9 9" fill="none" xmlns="http://www.w3.org/2000/svg" aria-label="Follow"><path d="M5 0H4V4H0V5H4V9H5V5H9V4H5V0Z"></path></svg></span></span><span>Emma Roth</span></span></span></p><p><span>إنها كاتبة أخبار تغطي حروب البث، التكنولوجيا الاستهلاكية، العملات المشفرة، وسائل التواصل الاجتماعي، وأكثر من ذلك. سابقاً، كانت كاتبة ومحررة في MUO.</span></p></div></div><div id="zephr-anchor"><p>كتبت مجموعة من أعضاء مجلس الشيوخ رسالة إلى الرئيس التنفيذي لشركة Meta، مارك زوكربيرج، تسأل عن سبب تأخير شركته في إطلاق الحماية الأساسية للمستخدمين تحت سن 18. تم توقيع الرسالة على يد براين شاتز (D-HI)، كاتي بريت (R-AL)، آمي كلوبوخر (D-MN)، جيمس لانكفورد (R-OK) وكريستوفر كونز (D-DE)، وتستشهد بالوثائق القضائية التي كشفت في آخر عام الماضي، التي كشفت ادعاءات بأن Meta قد قللت من أضرار منصاتها لصالح زيادة التفاعل مع المستخدمين.</p><p>بدأت Meta في وضع حسابات المراهقين على إنستغرام تلقائيًا في حسابات خاصة وأكثر تحديدًا في سبتمبر 2024، قبل أن توسع الحماية إلى فيسبوك وماسنجر في العام الماضي. ومع ذلك، توثق وثيقة قضائية غير محرّفة تم تقديمها في إطار دعوى على مستوى البلاد حول سلامة الأطفال على وسائل التواصل الاجتماعي أن Meta قد اعتبرت جعل جميع حسابات المراهقين خاصة في عام 2019، لكنه قرر بعد ذلك التخلي عن الخطة بعد أن وجد أنها "من المحتمل أن تقصف التفاعل".</p><p>في الرسالة، يطالب أعضاء مجلس الشيوخ زوكربيرج بمزيد من المعلومات حول سبب تأخير Meta لإطلاق ميزة الخصوصية الافتراضية للمراهقين، وكذلك عن الفرق المعنية بالقرار. كما يسلط الكتاب الضوء على بعض الاتهامات الأخرى المذكورة في الوثيقة القضائية، بما في ذلك ما إذا كان Meta قد أوقف يومًا أبحاثًا أو دراسات حول رفاهية المستخدمين ومنصاتها إذا كانت تنتج نتائج غير مرغوب فيها، كما ورد في الطلب.</p><p>“نحن قلقون بشدة من الادعاءات بأن Meta لم تكن على دراية فقط بهذه المخاطر، بل ربما أجلت تغييرات تصميم المنتج أو منع الإفصاح العام عن هذه النتائج”، حسب ما ورد في الرسالة.</p><p>كما يطالب السناتورز بالمزيد من التفاصيل حول سياسات Meta لرفع مواد الإساءة الجنسية للأطفال (CSAM) ومحتوى حول الاتجار الجنسي، بعد أن كشفت الوثيقة القضائية غير محرّفة شهادة رئيسة سلامة ورفاهية الشركة السابقة، التي ادّعت أن Meta ستعلق حساب شخص فقط بعد أن يتجاوز 17 انتهاكاً “للمحرضة على الدعارة والاستدراج”. يمنح السناتورز Meta مهلة حتى 6 مارس للرد على أسئلتهم.</p><div><p><span><strong>تابع الموضوعات والمؤلفين</strong> من هذه القصة لرؤية المزيد من المحتوى مشابه لهذا في خلاصة الصفحة الشخصية الخاصة بك والحصول على تحديثات عبر البريد الإلكتروني.</span></p><ul><li id="follow-author-article_footer-dmcyOmF1dGhvclByb2ZpbGU6MTE2"><span aria-expanded="false" aria-haspopup="true" role="button" tabindex="0"><span><span><svg width="9" height="9" viewBox="0 0 9 9" fill="none" xmlns="http://www.w3.org/2000/svg" aria-label="Follow"><path d="M5 0H4V4H0V5H4V9H5V5H9V4H5V0Z"></path></svg></span><span>Emma Roth</span></span></span></li><li></li><li></li><li></li><li></li><li></li></ul></div></div></div></div>	Emma Roth	The Verge	https://www.theverge.com/news/874158/senators-meta-teen-accounts-private-default	https://platform.theverge.com/wp-content/uploads/sites/2/2025/04/STKS507_FTCxMETA_ANTITRUST_CVIRGINIA_2_E.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200	2026-02-05 16:02:45+02	2026-02-16 22:49:49.04425+02
3	Translation API error 404\r\n﻿Black Myth: Wukong Sequel Releases Six-Minute Short Film To Celebrate Year Of The Horse	Translation API error 404\r\n﻿Created in Black Myth: Zhong Kui's engine, this is the most remarkable chef work	Translation API error 404\r\n﻿<div id="readability-page-1" class="page"><div><p>If you were expecting to see a second glimpse of Game Science’s follow-up to 2024’s break-out hit <em>Black Myth: Wukong</em>, this isn’t that. However, this brilliant short still promises much for what we can expect from <em>Black Myth: Zhong Kui</em>. This six-minute short film, created entirely in-engine, depicts the most extraordinary…cooking you’ve ever seen. It’s to celebrate Chinese New Year, and it’s truly special.</p><p>Expecting to see new monsters being hit with giant sticks and swords, I really wasn’t prepared for this wild-ass cookery demonstration set in the game’s mythical ancient China. This clip shows a studio still in a position of peak confidence, not least because none of what’s shown here is even part of the forthcoming game, described as “non-canon” and “unrelated to the main storyline.” It’s just a work of stunning gorgeousness to celebrate the Year of the Horse.</p><p>The demise of the blinking slab of meat was perhaps the most striking moment for me, in a film packed with extraordinary details and ruthless knife work. It’s there early on, dangling in the background, eyes just staring, unlikely to be noticed the first time you watch. It’s definitely worth watching at least twice.</p><p>While this doesn’t show the game in any sense at all, it’s also the most remarkable tech demo. Just the squishiness of the fish, for goodness sakes. And while the particle effects of dust and chopped leaves are still the weakest aspect, they’re the best I’ve ever seen. And the liquids are <em>crazy&nbsp;</em>good. And that’s not even mentioning the creature design.</p><p>This isn’t the first time Game Science has done this. In fact, it’s the sixth! The first was for <a href="https://www.youtube.com/watch?v=5oyu1y9dN4Y">2021’s Year of the Ox</a>, and was far more of a game trailer for <em>Black Myth: Wukong </em>than short film. 2022’s was a whole other kettle of cats, with <a href="https://www.youtube.com/watch?v=xPezz6HQm-I">a 12-minute mockumentary</a> about a fictional version of Game Science programming kittens into <em>Wukong</em> (completely with genuine motion capture footage!) to mark the Year of the Tiger. 2023’s Year of the Rabbit received <a href="https://www.youtube.com/watch?v=ERWqW7L9vU8">a stop-motion animation of a bunny</a> trying to get a PC version of a Game Science game working, while in 2024, for the Year of the Loong, the team put out <a href="https://www.youtube.com/watch?v=aqe2pSjh7S4">a 13-minute live-action dramatic film</a> complete with song. 2025 was <a href="https://www.youtube.com/watch?v=N_qVHZMo2ls">also a live-action short for the Year of the Snake</a>, but this time sneakily plugging a whole bunch of&nbsp;<em>Black Myth</em> merch to accompany its dramatic narrative rap.</p><p>So if anything, this year’s sixth New Year release is perhaps one of the more normal entries, given it’s made using the engine for the forthcoming <a href="https://kotaku.com/black-myth-2-gamescom-teaser-trailer-zhong-kui-game-science-china-2000618534"><em>Black Myth: Zhong Kui</em></a>, and names the game itself. Although I must note a distinct lack of horses. If you want to see more of what that’s actually intended to look like, a teaser trailer was released last year:</p></div></div>	John Walker	Kotaku	https://kotaku.com/black-myth-wukong-sequel-zhong-kui-trailer-new-year-2000667231	https://kotaku.com/app/uploads/2026/02/blackmyth2-1200x675.jpg	2026-02-10 15:07:44+02	2026-02-16 22:56:58.92885+02
5	يطرح مشروع الرعوية النوردية سؤالًا على الخيول عما إذا كانوا يفضلون البطانيات أم لا.	لقد قام الباحثون بتعليم الخيول التواصل عن تفضيلاتها باستخدام الرموز.	<div id="readability-page-1" class="page"><article>\r\n      <div><p>عندما يقتضى ذلك، أضع حشوة على الحصان الذي أركبه للتو دون تفكير ثانٍ، وبالتأكيد دون طلب إذنه. ومع ذلك، فإن مشروع يُدعى HorseVoice يمنح الخيول في النرويج والسويد صوتًا في هذا الشأن.</p><p>المسمى رسميًا بـ "إعطاء الحصان صوتًا – الرفاهية الحيوانية والتوعية للمالكين"، يهدف المشروع إلى تحقيق فهم أكبر لقدرات الخيول المعرفية، فضلاً عن حاجاتهم و تفضيلاتهم العاطفية، في أمل تحسين رفاهيتهم. يستخدم المشروع "طريقة الرموز" التي تم إنشاؤها سابقًا، حيث، كما يشير الاسم، يتم تعليم الخيول استخدام الرموز للتعبير عن رغبتها في ارتداء الحشوة أم لا. لا يمنح المشروع للخيول وكالة فحسب، بل يفتح الباب أيضًا لأسئلة أخلاقية معقدة—ماذا لو اتصل الخيول يومًا ما بأنهم لا يريدون أن يركبوا؟</p><h2>هل يلتزم؟ أم لا يلتزم بالحشوة؟</h2><p>«طلاب دراسات الخيول يدربون خيولهم الخاصة على استخدام طريقة الرموز، على سبيل المثال بعد التمرين، مع السماح للخيول باختيار ما إذا كان يريد ارتداء حشوة أم لا»، أوضحت غرييتة ه.م. يورجنسن، باحثة في معهد البحث البيولوجي النرويجي وقائدة للمشروع، في <a href="https://www.nibio.no/en/news/2026/new-research-project-gives-horses-a-voice">بيان</a> منشور من قبل المعهد. أظهرت الطريقة السابقة <a href="https://gizmodo.com/horses-can-use-symbols-to-communicate-their-desires-1786945655">أن الخيول يمكن أن تتواصل</a> معًا ما يرغبون به عبر الرموز. يشارك في المشروع طلاب من مركز الإحصاء الوطني للخيول في سترومسهمول السويدي ومؤسسة سكيتلين الثانوية العليا النرويجية.</p><figure id="attachment_2000714013" aria-describedby="caption-attachment-2000714013"><img decoding="async" src="https://gizmodo.com/app/uploads/2026/01/horse-iced-coffee.jpg" alt="قهوة باردة مع الخيول" width="1242" height="2208" srcset="https://gizmodo.com/app/uploads/2026/01/horse-iced-coffee.jpg 1242w, https://gizmodo.com/app/uploads/2026/01/horse-iced-coffee-189x336.jpg 189w, https://gizmodo.com/app/uploads/2026/01/horse-iced-coffee-720x1280.jpg 720w, https://gizmodo.com/app/uploads/2026/01/horse-iced-coffee-768x1365.jpg 768w, https://gizmodo.com/app/uploads/2026/01/horse-iced-coffee-378x672.jpg 378w, https://gizmodo.com/app/uploads/2026/01/horse-iced-coffee-540x960.jpg 540w, https://gizmodo.com/app/uploads/2026/01/horse-iced-coffee-900x1600.jpg 900w" sizes="(max-width: 639px) 100vw, (max-width: 1023px) calc(100vw - 2rem), (max-width: 1258px) calc((100vw - 3.68rem) * 2 / 3), 800px"><figcaption id="caption-attachment-2000714013">فرّق تعبيره عن تفضيله للقهوة الباردة (نكتة). © مارغريتا باسّي</figcaption></figure><p>يأتي المشروع فيما بعد فضائح في عالم رياضة الخيول الراقية بشأن سوء المعاملة للخيول، بما في ذلك <a href="https://www.usef.org/media/press-releases/fei-tribunal-imposes-fifteen-year-suspension-for">عقوبة تعليق لمدة 15 سنة</a> لراكب الألعاب الأولمبية سيزار باررا. وفي هذا السياق، يدرس الباحثون الآن أيضًا ما إذا كان استخدام طريقة الرموز يؤثر على وجهة نظركم للخيول. أي، هل سيتبين للطلاب أن الحيوانات هي كائنات فريدة ذات ميول ومتطلبات خاصة، بدلًا من كونها "مؤديين رياضيين".</p><p>«الكثير من الشباب يتأثرون بشخصيات مرجعية في عالم الخيول. عندما يُكشف أن بطلاً سابقًا تعامل مع الخيول بشكل سيء، يخلق ذلك حيرة وتفكيرًا. هذا المشروع يوفر مساحة لتلك الأنواع من المناقشات بالضبط»، صرحت يورجنسن. فريق HorseVoice، الذي يشمل مدرب حيوانات، يهدف إلى إنشاء دليل لطريقة الرموز للمدربين، مالكي الخيول، والمؤسسات التعليمية، ونشر النهج خارج نطاق المشروع. «إذا تعلم المزيد من الناس الاستماع إلى إشارات الخيول الخاصة، فقد يؤدي ذلك إلى تغييرات مستدامة في كل من المواقف والممارسات عبر قطاع الخيول بأكمله»، أضافت يورجنسن.</p><p>سيبقى لا يظهر ما سيخبرنا به الخيول التي تتدرب في طريقة الرموز حول تفضيلاتها لارتداء الحشوة بعد التمرين.</p><h2>تعليق من راكب</h2><p>كمحافظ على الخيول، أؤكد أن مع أن أغلبنا قد لا يسأل خيولنا عن تفضيلات الحشوة، إلا أن الأعضاء المسؤولين في مجتمع الخيول على وعي جيد بالاحتياجات الخاصة لكل حصان. لدى الخيول شخصيات، سلوكيات، ومخاوف صحية متباينة تمامًا. في دوغس أبس في ماساتشوستس، على سبيل المثال، يحتاج حصاننا المحبوب فرفلز إلى واقي شمس على أنفه خلال الصيف لتجنب حروق الشمس، ويستمتع بشكل واضح عندما تُماصّ نقاطه المتهيّجة (ألا أُضحك؛ سيرفع رجله مثل الكلب). أما العملاق الرحيم روبي، فهو حساس بشكل خاص لتغريم البعوض. المغني المتقاعد مجي كان خائفًا من الأبقار.</p><figure id="attachment_2000714012" aria-describedby="caption-attachment-2000714012"><img decoding="async" src="https://gizmodo.com/app/uploads/2026/01/davis-acres.jpeg" alt="ديفيس أكرز" width="1920" height="1440" srcset="https://gizmodo.com/app/uploads/2026/01/davis-acres.jpeg 1920w, https://gizmodo.com/app/uploads/2026/01/davis-acres-336x252.jpeg 336w, https://gizmodo.com/app/uploads/2026/01/davis-acres-1280x960.jpeg 1280w, https://gizmodo.com/app/uploads/2026/01/davis-acres-768x576.jpeg 768w, https://gizmodo.com/app/uploads/2026/01/davis-acres-672x504.jpeg 672w, https://gizmodo.com/app/uploads/2026/01/davis-acres-960x720.jpeg 960w, https://gizmodo.com/app/uploads/2026/01/davis-acres-1600x1200.jpeg 1600w" sizes="(max-width: 639px) 100vw, (max-width: 1023px) calc(100vw - 2rem), (max-width: 1258px) calc((100vw - 3.68rem) * 2 / 3), 800px"><figcaption id="caption-attachment-2000714012"> روبي (وسط)، فين (يسار)، وفرفلز (يمين) في مركز ديفيس أبس للخيول في ماساتشوستس. © مارغريتا باسّي</figcaption></figure><p>«من الناحية النظرية، لا توجد حدود لما يمكننا سؤاله عن الخيول—تفضيلها للمعدات، أو طرق التدريب، أو التغذية، أو السكن»، قالت يورجنسن. «في الوقت نفسه، هذا يجبرنا على التفكير في الأسئلة الأخلاقية. ماذا نفعل إذا اعتقد اختيار الحصان يختلف عن ما نريد؟ أو إذا قرر عدم الركوب على الإطلاق؟»</p><p>هذا بالفعل سؤال معقد. ومع ذلك، يشتمل سيناريو أقل فلسفة على حصان لا يرغب في ارتداء حشوة حتى عندما نعلم أن الحشوة ضرورية تمامًا—على سبيل المثال، إذا كان حصانًا متصببًا جدًا بعد درس مكثف، وهو بارد جدًا. ماذا نفعل حينئذٍ؟ في هذه الحالة الخاصة، أؤمن أن، مثلما مع الأطفال، يجب على البالغين أن يفعلوا ما هو الأفضل للخيول حتى لو لم يرغب الحصان في ما هو الأفضل لنفسه.</p><p>يعد الباحثون في HorseVoice أنهم غالبًا لا ندرك كيف يشعر الخيول. وعلى الرغم من أن هذا قد يكون صحيحًا، فإن أداة الأكثر أهمية في هذا المفهوم هي مدى شعور الخيول بالانزعاج الصحي. بمعنى آخر، ما إذا كان حصانًا تريد حشوة أم لا هو أقل أهمية من معرفة أن الحصان غير مرتاح.</p><p>باختصار، لا أستطيع الانتظار لطريقة رموز تساعد الخيول على التواصل حول أعراضها الطبية.</p></div>\r\n    </article></div>	Margherita Bassi	Gizmodo.com	https://gizmodo.com/nordic-equestrian-project-asks-horses-if-they-want-blankets-or-not-2000714006	https://gizmodo.com/app/uploads/2026/01/horse-communicating-with-symbols-1200x675.jpg	2026-01-26 23:45:38+02	2026-02-16 23:04:45.384841+02
\.


--
-- Data for Name: owners; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.owners (owner_id, preferences, since) FROM stdin;
2	\N	2026-01-18 13:26:31.649772+02
\.


--
-- Data for Name: pedigrees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pedigrees (ped_id, father_horse_name, mother_horse_name, lineage_notes) FROM stdin;
\.


--
-- Data for Name: role_claims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role_claims (id, role_id, claim_type, claim_value) FROM stdin;
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, name, normalized_name, concurrency_stamp) FROM stdin;
1	Admin	ADMIN	ab87f518-4473-41ea-8960-12285fa0793b
\.


--
-- Data for Name: stud_phones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stud_phones (phone_id, stud_id, phone_number) FROM stdin;
\.


--
-- Data for Name: studs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.studs (stud_id, name, stud_type, stall_capacity, boarding_price, num_of_horses, num_of_males, num_of_females, url, location_id) FROM stdin;
\.


--
-- Data for Name: trainers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trainers (trainer_id, experience_years, bio) FROM stdin;
\.


--
-- Data for Name: training_programmes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.training_programmes (program_id, name_of_program, description, start_date, end_date, price, trainer_id, manege_id) FROM stdin;
\.


--
-- Data for Name: user_claims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_claims (id, user_id, claim_type, claim_value) FROM stdin;
\.


--
-- Data for Name: user_logins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_logins (login_provider, provider_key, provider_display_name, user_id) FROM stdin;
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (user_id, role_id) FROM stdin;
2	1
8	1
\.


--
-- Data for Name: user_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_tokens (user_id, login_provider, name, value) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, name, created_at, user_name, email, password_hash, phone, access_failed_count, concurrency_stamp, email_confirmed, lockout_enabled, lockout_end, normalized_email, normalized_user_name, phone_number_confirmed, security_stamp, two_factor_enabled, role, bio, profile_picture_url, last_password_changed_at, is_verified_bidder) FROM stdin;
1	Fixed User	2026-01-10 23:34:59.348431+02	final_fix@test.com	final_fix@test.com	AQAAAAIAAYagAAAAEPZh+b49ZxjBuqMG3xYIxpIutjDectBCzvzkEwP1NtWhHlqUJprULn+p2y9xcs+F9Q==	\N	0	2406027d-b8bc-4f96-bbf2-4d87b7590629	f	t	\N	FINAL_FIX@TEST.COM	FINAL_FIX@TEST.COM	f	AZBPSL6GLWWPORFYQN47YGY4AM4BWME7	f	\N	\N	\N	\N	f
4	Test User Two	2026-01-11 12:33:23.076209+02	test2@example.com	test2@example.com	AQAAAAIAAYagAAAAEBDaXyG2wPu5radbrAtaFQX/sC2e2Af+tz63AqUSEMP3BDaZ0Nzm1Wr9RKQ5BZyL0g==	\N	0	494f9c0d-68f6-4d84-9a51-505b6b55a109	f	t	\N	TEST2@EXAMPLE.COM	TEST2@EXAMPLE.COM	f	4RGR5HUMEV4JHGOYZ5UXS7GOVSJGRSBH	f	\N	\N	\N	\N	f
5	Test User	2026-01-11 13:33:52.259609+02	test_user_final@example.com	test_user_final@example.com	AQAAAAIAAYagAAAAEGnivTm7GpT8A/3F1AoOBVGRH9LkhDoQLF4kziiBJWaIDL4plNU7V0sAtvoI387rkw==	\N	0	3e66142c-4a8e-461d-872b-49c31ba1298b	f	t	\N	TEST_USER_FINAL@EXAMPLE.COM	TEST_USER_FINAL@EXAMPLE.COM	f	64OINZYOQLSIVOIFJQCFBLBI2LXX7QIM	f	\N	\N	\N	\N	f
6	Admin Test	2026-01-15 18:24:43.738027+02	admin_test@test.com	admin_test@test.com	AQAAAAIAAYagAAAAEIef2XN4DwKF4rIMDRHBlJvE7eiFsW7NV8t56nxn6urZXXyx5hcSclq4YnuYCr+FAA==	\N	0	1679c268-f665-4ba3-94ed-d4fd98c5ccf4	f	t	\N	ADMIN_TEST@TEST.COM	ADMIN_TEST@TEST.COM	f	J7GASP26WG4V5BNZY2MRIFMEFF5ZAGY6	f	\N	\N	\N	\N	f
7	System Admin	2026-01-15 19:56:05.989023+02	mohamed_final_attempt_999@gmail.com	mohamed_final_attempt_999@gmail.com	AQAAAAIAAYagAAAAELmvii8ikldNLlrVX+nNXsScQsPTl2foYP3+q1mkg8Qh67DTUneRHNlvbMJafzzeIw==	\N	0	156824aa-f838-4976-90c2-8475e8791635	f	t	\N	MOHAMED_FINAL_ATTEMPT_999@GMAIL.COM	MOHAMED_FINAL_ATTEMPT_999@GMAIL.COM	f	VSFPN3MZRUKSMG5HEYB6E56WVXSVROBJ	f	\N	\N	\N	\N	f
2	mohamed mostafa 	2026-01-11 00:12:29.808295+02	mohamed200031921@gmail.com	mohamed200031921@gmail.com	AQAAAAIAAYagAAAAECoDFAs7RJVUb4mswpWH4TwzWktdVsg31zZHodid+MfOo8qP7VskKtfe/Q22kYBznQ==	01030469659	0	8ba85466-764e-42fa-94cb-7216916b4367	f	t	\N	MOHAMED200031921@GMAIL.COM	MOHAMED200031921@GMAIL.COM	f	KLHUQBXJN3B5GBJY4MBSFZM7JXFHMAQP	f	Admin	\N	/uploads/f25459cc-1224-4ea0-a958-f1329122953b.png	2026-02-13 00:09:34.028098+02	t
8	System Admin	2026-01-15 20:24:55.55559+02	testadmin@gmail.com	testadmin@gmail.com	AQAAAAIAAYagAAAAEMdrA48zrjaRNU/ULWw2X6dJXJ8v4ghUvuB2qLjH13nZT6Wgtr0nVbcJ2oMrs/39/w==	\N	0	0f8ae77b-b8a7-4d7e-a2ef-9d4bf4989775	f	t	\N	TESTADMIN@GMAIL.COM	TESTADMIN@GMAIL.COM	f	WIV5XM5D4XXXHG2UM5LAZDBWPT4DEL4M	f	Admin	\N	\N	\N	f
3	Test User	2026-01-11 12:24:26.568623+02	test@example.com	test@example.com	AQAAAAIAAYagAAAAEA8U+IFl2v1Rs6H20T+7mZ8R1au/eTS4WzcXQzVEoa7elKnTdl+gBqG8b/fxrfKHXA==	\N	0	b4bb3437-732d-41a4-a6e5-98897f6e056a	f	t	\N	TEST@EXAMPLE.COM	TEST@EXAMPLE.COM	f	AAWW37BW3GBEDGGRHOZ33WHB64WAAYDY	f	EquineVet	\N	\N	\N	f
9	NormalUser	2026-01-16 14:56:40.707121+02	normaluser@gmail.com	normaluser@gmail.com	AQAAAAIAAYagAAAAEKdIcySwkW7GQY9B7nAn4iPhxDwUyo+rt3saDd/TyS20oENmrCCAfkCNmVQJ8ZGq+w==	\N	0	bfca1e1d-3d8b-4212-9d1a-6a380a0d6638	f	t	\N	NORMALUSER@GMAIL.COM	NORMALUSER@GMAIL.COM	f	RUJZOJQC2NUSF2KCNLAWMH3GJ4YFWG2G	f	Seller	\N	\N	2026-01-30 21:43:57.983042+02	f
\.


--
-- Name: auctions_auction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auctions_auction_id_seq', 7, true);


--
-- Name: bids_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bids_id_seq', 1, false);


--
-- Name: colours_colour_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.colours_colour_id_seq', 1, false);


--
-- Name: health_records_health_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.health_records_health_id_seq', 1, false);


--
-- Name: horse_training_enrollments_enrollment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.horse_training_enrollments_enrollment_id_seq', 1, false);


--
-- Name: locations_location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.locations_location_id_seq', 1, false);


--
-- Name: maneges_manege_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.maneges_manege_id_seq', 1, false);


--
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messages_id_seq', 5, true);


--
-- Name: news_posts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.news_posts_id_seq', 5, true);


--
-- Name: pedigrees_ped_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pedigrees_ped_id_seq', 1, false);


--
-- Name: role_claims_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_claims_id_seq', 1, false);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 1, true);


--
-- Name: stud_phones_phone_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.stud_phones_phone_id_seq', 1, false);


--
-- Name: studs_stud_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.studs_stud_id_seq', 1, false);


--
-- Name: training_programmes_program_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.training_programmes_program_id_seq', 1, false);


--
-- Name: user_claims_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_claims_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 9, true);


--
-- Name: __EFMigrationsHistory pk___ef_migrations_history; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id);


--
-- Name: auctions pk_auctions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT pk_auctions PRIMARY KEY (auction_id);


--
-- Name: bids pk_bids; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bids
    ADD CONSTRAINT pk_bids PRIMARY KEY (id);


--
-- Name: colours pk_colours; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.colours
    ADD CONSTRAINT pk_colours PRIMARY KEY (colour_id);


--
-- Name: equine_vets pk_equine_vets; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equine_vets
    ADD CONSTRAINT pk_equine_vets PRIMARY KEY (vet_id);


--
-- Name: health_records pk_health_records; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_records
    ADD CONSTRAINT pk_health_records PRIMARY KEY (health_id);


--
-- Name: horse_profiles pk_horse_profiles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.horse_profiles
    ADD CONSTRAINT pk_horse_profiles PRIMARY KEY (microchip_id);


--
-- Name: horse_training_enrollments pk_horse_training_enrollments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.horse_training_enrollments
    ADD CONSTRAINT pk_horse_training_enrollments PRIMARY KEY (enrollment_id);


--
-- Name: locations pk_locations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT pk_locations PRIMARY KEY (location_id);


--
-- Name: maneges pk_maneges; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maneges
    ADD CONSTRAINT pk_maneges PRIMARY KEY (manege_id);


--
-- Name: messages pk_messages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT pk_messages PRIMARY KEY (id);


--
-- Name: news_posts pk_news_posts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news_posts
    ADD CONSTRAINT pk_news_posts PRIMARY KEY (id);


--
-- Name: owners pk_owners; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.owners
    ADD CONSTRAINT pk_owners PRIMARY KEY (owner_id);


--
-- Name: pedigrees pk_pedigrees; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedigrees
    ADD CONSTRAINT pk_pedigrees PRIMARY KEY (ped_id);


--
-- Name: role_claims pk_role_claims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_claims
    ADD CONSTRAINT pk_role_claims PRIMARY KEY (id);


--
-- Name: roles pk_roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT pk_roles PRIMARY KEY (id);


--
-- Name: stud_phones pk_stud_phones; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stud_phones
    ADD CONSTRAINT pk_stud_phones PRIMARY KEY (phone_id);


--
-- Name: studs pk_studs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studs
    ADD CONSTRAINT pk_studs PRIMARY KEY (stud_id);


--
-- Name: trainers pk_trainers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainers
    ADD CONSTRAINT pk_trainers PRIMARY KEY (trainer_id);


--
-- Name: training_programmes pk_training_programmes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.training_programmes
    ADD CONSTRAINT pk_training_programmes PRIMARY KEY (program_id);


--
-- Name: user_claims pk_user_claims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_claims
    ADD CONSTRAINT pk_user_claims PRIMARY KEY (id);


--
-- Name: user_logins pk_user_logins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_logins
    ADD CONSTRAINT pk_user_logins PRIMARY KEY (login_provider, provider_key);


--
-- Name: user_roles pk_user_roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id);


--
-- Name: user_tokens pk_user_tokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_tokens
    ADD CONSTRAINT pk_user_tokens PRIMARY KEY (user_id, login_provider, name);


--
-- Name: users pk_users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT pk_users PRIMARY KEY (user_id);


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public.users USING btree (normalized_email);


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public.roles USING btree (normalized_name);


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public.users USING btree (normalized_user_name);


--
-- Name: ix_auctions_created_by_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_auctions_created_by_id ON public.auctions USING btree (created_by_id);


--
-- Name: ix_auctions_location_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_auctions_location_id ON public.auctions USING btree (location_id);


--
-- Name: ix_auctions_microchip_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_auctions_microchip_id ON public.auctions USING btree (microchip_id);


--
-- Name: ix_auctions_winner_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_auctions_winner_id ON public.auctions USING btree (winner_id);


--
-- Name: ix_bids_auction_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_bids_auction_id ON public.bids USING btree (auction_id);


--
-- Name: ix_bids_bidder_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_bids_bidder_id ON public.bids USING btree (bidder_id);


--
-- Name: ix_health_records_microchip_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_health_records_microchip_id ON public.health_records USING btree (microchip_id);


--
-- Name: ix_health_records_vet_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_health_records_vet_id ON public.health_records USING btree (vet_id);


--
-- Name: ix_horse_profiles_colour_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_horse_profiles_colour_id ON public.horse_profiles USING btree (colour_id);


--
-- Name: ix_horse_profiles_owner_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_horse_profiles_owner_id ON public.horse_profiles USING btree (owner_id);


--
-- Name: ix_horse_profiles_pedigree_ped_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_horse_profiles_pedigree_ped_id ON public.horse_profiles USING btree (pedigree_ped_id);


--
-- Name: ix_horse_profiles_stud_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_horse_profiles_stud_id ON public.horse_profiles USING btree (stud_id);


--
-- Name: ix_horse_training_enrollments_microchip_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_horse_training_enrollments_microchip_id ON public.horse_training_enrollments USING btree (microchip_id);


--
-- Name: ix_horse_training_enrollments_program_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_horse_training_enrollments_program_id ON public.horse_training_enrollments USING btree (program_id);


--
-- Name: ix_maneges_location_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_maneges_location_id ON public.maneges USING btree (location_id);


--
-- Name: ix_messages_receiver_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_messages_receiver_id ON public.messages USING btree (receiver_id);


--
-- Name: ix_messages_sender_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_messages_sender_id ON public.messages USING btree (sender_id);


--
-- Name: ix_role_claims_role_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_role_claims_role_id ON public.role_claims USING btree (role_id);


--
-- Name: ix_stud_phones_stud_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_stud_phones_stud_id ON public.stud_phones USING btree (stud_id);


--
-- Name: ix_studs_location_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_studs_location_id ON public.studs USING btree (location_id);


--
-- Name: ix_training_programmes_manege_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_training_programmes_manege_id ON public.training_programmes USING btree (manege_id);


--
-- Name: ix_training_programmes_trainer_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_training_programmes_trainer_id ON public.training_programmes USING btree (trainer_id);


--
-- Name: ix_user_claims_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_user_claims_user_id ON public.user_claims USING btree (user_id);


--
-- Name: ix_user_logins_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_user_logins_user_id ON public.user_logins USING btree (user_id);


--
-- Name: ix_user_roles_role_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_user_roles_role_id ON public.user_roles USING btree (role_id);


--
-- Name: auctions fk_auctions_horse_profiles_microchip_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT fk_auctions_horse_profiles_microchip_id FOREIGN KEY (microchip_id) REFERENCES public.horse_profiles(microchip_id);


--
-- Name: auctions fk_auctions_locations_location_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT fk_auctions_locations_location_id FOREIGN KEY (location_id) REFERENCES public.locations(location_id);


--
-- Name: auctions fk_auctions_users_created_by_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT fk_auctions_users_created_by_id FOREIGN KEY (created_by_id) REFERENCES public.users(user_id);


--
-- Name: auctions fk_auctions_users_winner_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT fk_auctions_users_winner_id FOREIGN KEY (winner_id) REFERENCES public.users(user_id);


--
-- Name: bids fk_bids_auctions_auction_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bids
    ADD CONSTRAINT fk_bids_auctions_auction_id FOREIGN KEY (auction_id) REFERENCES public.auctions(auction_id) ON DELETE CASCADE;


--
-- Name: bids fk_bids_users_bidder_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bids
    ADD CONSTRAINT fk_bids_users_bidder_id FOREIGN KEY (bidder_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: equine_vets fk_equine_vets_users_vet_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equine_vets
    ADD CONSTRAINT fk_equine_vets_users_vet_id FOREIGN KEY (vet_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: health_records fk_health_records_equine_vets_vet_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_records
    ADD CONSTRAINT fk_health_records_equine_vets_vet_id FOREIGN KEY (vet_id) REFERENCES public.equine_vets(vet_id);


--
-- Name: health_records fk_health_records_horse_profiles_microchip_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_records
    ADD CONSTRAINT fk_health_records_horse_profiles_microchip_id FOREIGN KEY (microchip_id) REFERENCES public.horse_profiles(microchip_id) ON DELETE CASCADE;


--
-- Name: horse_profiles fk_horse_profiles_colours_colour_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.horse_profiles
    ADD CONSTRAINT fk_horse_profiles_colours_colour_id FOREIGN KEY (colour_id) REFERENCES public.colours(colour_id);


--
-- Name: horse_profiles fk_horse_profiles_owners_owner_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.horse_profiles
    ADD CONSTRAINT fk_horse_profiles_owners_owner_id FOREIGN KEY (owner_id) REFERENCES public.owners(owner_id);


--
-- Name: horse_profiles fk_horse_profiles_pedigrees_pedigree_ped_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.horse_profiles
    ADD CONSTRAINT fk_horse_profiles_pedigrees_pedigree_ped_id FOREIGN KEY (pedigree_ped_id) REFERENCES public.pedigrees(ped_id);


--
-- Name: horse_profiles fk_horse_profiles_studs_stud_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.horse_profiles
    ADD CONSTRAINT fk_horse_profiles_studs_stud_id FOREIGN KEY (stud_id) REFERENCES public.studs(stud_id);


--
-- Name: horse_training_enrollments fk_horse_training_enrollments_horse_profiles_microchip_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.horse_training_enrollments
    ADD CONSTRAINT fk_horse_training_enrollments_horse_profiles_microchip_id FOREIGN KEY (microchip_id) REFERENCES public.horse_profiles(microchip_id) ON DELETE CASCADE;


--
-- Name: horse_training_enrollments fk_horse_training_enrollments_training_programmes_program_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.horse_training_enrollments
    ADD CONSTRAINT fk_horse_training_enrollments_training_programmes_program_id FOREIGN KEY (program_id) REFERENCES public.training_programmes(program_id) ON DELETE CASCADE;


--
-- Name: maneges fk_maneges_locations_location_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maneges
    ADD CONSTRAINT fk_maneges_locations_location_id FOREIGN KEY (location_id) REFERENCES public.locations(location_id);


--
-- Name: messages fk_messages_users_receiver_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_messages_users_receiver_id FOREIGN KEY (receiver_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: messages fk_messages_users_sender_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_messages_users_sender_id FOREIGN KEY (sender_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: owners fk_owners_users_owner_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.owners
    ADD CONSTRAINT fk_owners_users_owner_id FOREIGN KEY (owner_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: role_claims fk_role_claims_roles_role_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_claims
    ADD CONSTRAINT fk_role_claims_roles_role_id FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- Name: stud_phones fk_stud_phones_studs_stud_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stud_phones
    ADD CONSTRAINT fk_stud_phones_studs_stud_id FOREIGN KEY (stud_id) REFERENCES public.studs(stud_id) ON DELETE CASCADE;


--
-- Name: studs fk_studs_locations_location_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studs
    ADD CONSTRAINT fk_studs_locations_location_id FOREIGN KEY (location_id) REFERENCES public.locations(location_id);


--
-- Name: trainers fk_trainers_users_trainer_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainers
    ADD CONSTRAINT fk_trainers_users_trainer_id FOREIGN KEY (trainer_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: training_programmes fk_training_programmes_maneges_manege_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.training_programmes
    ADD CONSTRAINT fk_training_programmes_maneges_manege_id FOREIGN KEY (manege_id) REFERENCES public.maneges(manege_id);


--
-- Name: training_programmes fk_training_programmes_trainers_trainer_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.training_programmes
    ADD CONSTRAINT fk_training_programmes_trainers_trainer_id FOREIGN KEY (trainer_id) REFERENCES public.trainers(trainer_id);


--
-- Name: user_claims fk_user_claims_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_claims
    ADD CONSTRAINT fk_user_claims_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_logins fk_user_logins_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_logins
    ADD CONSTRAINT fk_user_logins_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_roles fk_user_roles_roles_role_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_roles_role_id FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- Name: user_roles fk_user_roles_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_tokens fk_user_tokens_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_tokens
    ADD CONSTRAINT fk_user_tokens_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict Pn1lVhVaMSpbaxF9nG9MOznGUlSDA6rrzwflaOX9FVZYoSgkTgiIZ7vXa3j37vN

