// <auto-generated />
using System;
using ArabianHorseSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArabianHorseSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260130213350_AddIsVerifiedBidder")]
    partial class AddIsVerifiedBidder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArabianHorseSystem.Models.Auction", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("auction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuctionId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("base_price");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<decimal>("CurrentBid")
                        .HasColumnType("numeric")
                        .HasColumnName("current_bid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("InsuranceDetails")
                        .HasColumnType("text")
                        .HasColumnName("insurance_details");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("MicrochipId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("microchip_id");

                    b.Property<decimal>("MinimumIncrement")
                        .HasColumnType("numeric")
                        .HasColumnName("minimum_increment");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("video_url");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer")
                        .HasColumnName("winner_id");

                    b.HasKey("AuctionId")
                        .HasName("pk_auctions");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_auctions_created_by_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_auctions_location_id");

                    b.HasIndex("MicrochipId")
                        .HasDatabaseName("ix_auctions_microchip_id");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("ix_auctions_winner_id");

                    b.ToTable("auctions", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer")
                        .HasColumnName("auction_id");

                    b.Property<int>("BidderId")
                        .HasColumnType("integer")
                        .HasColumnName("bidder_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_bids");

                    b.HasIndex("AuctionId")
                        .HasDatabaseName("ix_bids_auction_id");

                    b.HasIndex("BidderId")
                        .HasDatabaseName("ix_bids_bidder_id");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Colour", b =>
                {
                    b.Property<int>("ColourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("colour_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ColourId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("ColourId")
                        .HasName("pk_colours");

                    b.ToTable("colours", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.EquineVet", b =>
                {
                    b.Property<int>("VetId")
                        .HasColumnType("integer")
                        .HasColumnName("vet_id");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ssn");

                    b.Property<string>("VeterinaryLicense")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("veterinary_license");

                    b.HasKey("VetId")
                        .HasName("pk_equine_vets");

                    b.ToTable("equine_vets", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.HealthRecord", b =>
                {
                    b.Property<int>("HealthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("health_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HealthId"));

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnosis");

                    b.Property<string>("MicrochipId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("microchip_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("treatment");

                    b.Property<int?>("VetId")
                        .HasColumnType("integer")
                        .HasColumnName("vet_id");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visit_date");

                    b.HasKey("HealthId")
                        .HasName("pk_health_records");

                    b.HasIndex("MicrochipId")
                        .HasDatabaseName("ix_health_records_microchip_id");

                    b.HasIndex("VetId")
                        .HasDatabaseName("ix_health_records_vet_id");

                    b.ToTable("health_records", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.HorseProfile", b =>
                {
                    b.Property<string>("MicrochipId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("microchip_id");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthdate");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("breed");

                    b.Property<string>("ClaimLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("claim_location");

                    b.Property<int?>("ColourId")
                        .HasColumnType("integer")
                        .HasColumnName("colour_id");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("health_status");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_sale");

                    b.Property<string>("LifeStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("life_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<int?>("PedId")
                        .HasColumnType("integer")
                        .HasColumnName("ped_id");

                    b.Property<string>("PedigreeImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pedigree_image_url");

                    b.Property<int?>("PedigreePedId")
                        .HasColumnType("integer")
                        .HasColumnName("pedigree_ped_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("RacingHistory")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("racing_history");

                    b.Property<int?>("StudId")
                        .HasColumnType("integer")
                        .HasColumnName("stud_id");

                    b.Property<bool>("Vaccinated")
                        .HasColumnType("boolean")
                        .HasColumnName("vaccinated");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("video_url");

                    b.HasKey("MicrochipId")
                        .HasName("pk_horse_profiles");

                    b.HasIndex("ColourId")
                        .HasDatabaseName("ix_horse_profiles_colour_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_horse_profiles_owner_id");

                    b.HasIndex("PedigreePedId")
                        .HasDatabaseName("ix_horse_profiles_pedigree_ped_id");

                    b.HasIndex("StudId")
                        .HasDatabaseName("ix_horse_profiles_stud_id");

                    b.ToTable("horse_profiles", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.HorseTrainingEnrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrollment_date");

                    b.Property<string>("MicrochipId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("microchip_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("PerformanceScore")
                        .HasColumnType("integer")
                        .HasColumnName("performance_score");

                    b.Property<int>("ProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("program_id");

                    b.HasKey("EnrollmentId")
                        .HasName("pk_horse_training_enrollments");

                    b.HasIndex("MicrochipId")
                        .HasDatabaseName("ix_horse_training_enrollments_microchip_id");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("ix_horse_training_enrollments_program_id");

                    b.ToTable("horse_training_enrollments", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Government")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("government");

                    b.HasKey("LocationId")
                        .HasName("pk_locations");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Manege", b =>
                {
                    b.Property<int>("ManegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("manege_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ManegeId"));

                    b.Property<string>("AvailabilitySchedule")
                        .HasColumnType("text")
                        .HasColumnName("availability_schedule");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SurfaceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surface_type");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("ManegeId")
                        .HasName("pk_maneges");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_maneges_location_id");

                    b.ToTable("maneges", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("HorseId")
                        .HasColumnType("text")
                        .HasColumnName("horse_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_messages_receiver_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_messages_sender_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.NewsPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SourceName")
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("UrlToImage")
                        .HasColumnType("text")
                        .HasColumnName("url_to_image");

                    b.HasKey("Id")
                        .HasName("pk_news_posts");

                    b.ToTable("news_posts", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("Preferences")
                        .HasColumnType("jsonb")
                        .HasColumnName("preferences");

                    b.Property<DateTime>("Since")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("since");

                    b.HasKey("OwnerId")
                        .HasName("pk_owners");

                    b.ToTable("owners", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Pedigree", b =>
                {
                    b.Property<int>("PedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ped_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PedId"));

                    b.Property<string>("FatherHorseName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("father_horse_name");

                    b.Property<string>("LineageNotes")
                        .HasColumnType("text")
                        .HasColumnName("lineage_notes");

                    b.Property<string>("MotherHorseName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("mother_horse_name");

                    b.HasKey("PedId")
                        .HasName("pk_pedigrees");

                    b.ToTable("pedigrees", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Stud", b =>
                {
                    b.Property<int>("StudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stud_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudId"));

                    b.Property<decimal>("BoardingPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("boarding_price");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("NumOfFemales")
                        .HasColumnType("integer")
                        .HasColumnName("num_of_females");

                    b.Property<int>("NumOfHorses")
                        .HasColumnType("integer")
                        .HasColumnName("num_of_horses");

                    b.Property<int>("NumOfMales")
                        .HasColumnType("integer")
                        .HasColumnName("num_of_males");

                    b.Property<int>("StallCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("stall_capacity");

                    b.Property<string>("StudType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stud_type");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url");

                    b.HasKey("StudId")
                        .HasName("pk_studs");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_studs_location_id");

                    b.ToTable("studs", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.StudPhone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("phone_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhoneId"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("StudId")
                        .HasColumnType("integer")
                        .HasColumnName("stud_id");

                    b.HasKey("PhoneId")
                        .HasName("pk_stud_phones");

                    b.HasIndex("StudId")
                        .HasDatabaseName("ix_stud_phones_stud_id");

                    b.ToTable("stud_phones", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .HasColumnType("integer")
                        .HasColumnName("trainer_id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_years");

                    b.HasKey("TrainerId")
                        .HasName("pk_trainers");

                    b.ToTable("trainers", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.TrainingProgramme", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("program_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int?>("ManegeId")
                        .HasColumnType("integer")
                        .HasColumnName("manege_id");

                    b.Property<string>("NameOfProgram")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_of_program");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("integer")
                        .HasColumnName("trainer_id");

                    b.HasKey("ProgramId")
                        .HasName("pk_training_programmes");

                    b.HasIndex("ManegeId")
                        .HasDatabaseName("ix_training_programmes_manege_id");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("ix_training_programmes_trainer_id");

                    b.ToTable("training_programmes", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("IsVerifiedBidder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified_bidder");

                    b.Property<DateTime?>("LastPasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_password_changed_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Auction", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_auctions_users_created_by_id");

                    b.HasOne("ArabianHorseSystem.Models.Location", "Location")
                        .WithMany("Auctions")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("fk_auctions_locations_location_id");

                    b.HasOne("ArabianHorseSystem.Models.HorseProfile", "Horse")
                        .WithMany("Auctions")
                        .HasForeignKey("MicrochipId")
                        .HasConstraintName("fk_auctions_horse_profiles_microchip_id");

                    b.HasOne("ArabianHorseSystem.Models.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .HasConstraintName("fk_auctions_users_winner_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Horse");

                    b.Navigation("Location");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Bid", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bids_auctions_auction_id");

                    b.HasOne("ArabianHorseSystem.Models.User", "Bidder")
                        .WithMany()
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bids_users_bidder_id");

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.EquineVet", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.User", "User")
                        .WithOne("VetProfile")
                        .HasForeignKey("ArabianHorseSystem.Models.EquineVet", "VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equine_vets_users_vet_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.HealthRecord", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.HorseProfile", "Horse")
                        .WithMany("HealthRecords")
                        .HasForeignKey("MicrochipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_records_horse_profiles_microchip_id");

                    b.HasOne("ArabianHorseSystem.Models.EquineVet", "Vet")
                        .WithMany("HealthRecords")
                        .HasForeignKey("VetId")
                        .HasConstraintName("fk_health_records_equine_vets_vet_id");

                    b.Navigation("Horse");

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.HorseProfile", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.Colour", "Colour")
                        .WithMany("Horses")
                        .HasForeignKey("ColourId")
                        .HasConstraintName("fk_horse_profiles_colours_colour_id");

                    b.HasOne("ArabianHorseSystem.Models.Owner", "Owner")
                        .WithMany("Horses")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("fk_horse_profiles_owners_owner_id");

                    b.HasOne("ArabianHorseSystem.Models.Pedigree", "Pedigree")
                        .WithMany("Horses")
                        .HasForeignKey("PedigreePedId")
                        .HasConstraintName("fk_horse_profiles_pedigrees_pedigree_ped_id");

                    b.HasOne("ArabianHorseSystem.Models.Stud", "Stud")
                        .WithMany("Horses")
                        .HasForeignKey("StudId")
                        .HasConstraintName("fk_horse_profiles_studs_stud_id");

                    b.Navigation("Colour");

                    b.Navigation("Owner");

                    b.Navigation("Pedigree");

                    b.Navigation("Stud");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.HorseTrainingEnrollment", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.HorseProfile", "Horse")
                        .WithMany("Enrollments")
                        .HasForeignKey("MicrochipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_horse_training_enrollments_horse_profiles_microchip_id");

                    b.HasOne("ArabianHorseSystem.Models.TrainingProgramme", "Program")
                        .WithMany("Enrollments")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_horse_training_enrollments_training_programmes_program_id");

                    b.Navigation("Horse");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Manege", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.Location", "Location")
                        .WithMany("Maneges")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("fk_maneges_locations_location_id");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Message", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_receiver_id");

                    b.HasOne("ArabianHorseSystem.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_sender_id");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Owner", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.User", "User")
                        .WithOne("OwnerProfile")
                        .HasForeignKey("ArabianHorseSystem.Models.Owner", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_owners_users_owner_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Stud", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.Location", "Location")
                        .WithMany("Studs")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("fk_studs_locations_location_id");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.StudPhone", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.Stud", "Stud")
                        .WithMany("Phones")
                        .HasForeignKey("StudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stud_phones_studs_stud_id");

                    b.Navigation("Stud");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Trainer", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.User", "User")
                        .WithOne("TrainerProfile")
                        .HasForeignKey("ArabianHorseSystem.Models.Trainer", "TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trainers_users_trainer_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.TrainingProgramme", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.Manege", "Manege")
                        .WithMany("TrainingProgrammes")
                        .HasForeignKey("ManegeId")
                        .HasConstraintName("fk_training_programmes_maneges_manege_id");

                    b.HasOne("ArabianHorseSystem.Models.Trainer", "Trainer")
                        .WithMany("TrainingProgrammes")
                        .HasForeignKey("TrainerId")
                        .HasConstraintName("fk_training_programmes_trainers_trainer_id");

                    b.Navigation("Manege");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("ArabianHorseSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ArabianHorseSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Colour", b =>
                {
                    b.Navigation("Horses");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.EquineVet", b =>
                {
                    b.Navigation("HealthRecords");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.HorseProfile", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Enrollments");

                    b.Navigation("HealthRecords");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Location", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Maneges");

                    b.Navigation("Studs");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Manege", b =>
                {
                    b.Navigation("TrainingProgrammes");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Owner", b =>
                {
                    b.Navigation("Horses");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Pedigree", b =>
                {
                    b.Navigation("Horses");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Stud", b =>
                {
                    b.Navigation("Horses");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.Trainer", b =>
                {
                    b.Navigation("TrainingProgrammes");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.TrainingProgramme", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("ArabianHorseSystem.Models.User", b =>
                {
                    b.Navigation("OwnerProfile");

                    b.Navigation("TrainerProfile");

                    b.Navigation("VetProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
